language: python
dist: trusty
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
env:
  - PYTHONPATH=.
install: pip install -Ue .
script: python setup.py test
after_success:
  - nosetest --with-coverage
  - bash <(curl -s https://codecov.io/bash)
