language: python
dist: trusty
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
env:
  - PYTHONPATH=.
install:
  - pip install -Ue .
  - pip install -U nose coverage
script: python setup.py test
after_success:
  - nosetests --with-coverage --cover-package=b4m
  - bash <(curl -s https://codecov.io/bash)
