language: python
dist: trusty
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
install: pip install -Ue .
script: python b4m/libs/encryptor.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
